name: "Build with provenance"
on:
  workflow_dispatch:
    inputs:
      flakeref:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build with provenance
      id: build
      uses: joinemm/nix-provenance/build-wrapper@master
      with:
        flakeref: ${{ github.event.inputs.flakeref }}

    - name: Preview provenance
      run: cat ${{ steps.build.outputs.provenance }} | jq .

    - name: Upload provenance artifact
      uses: actions/upload-artifact@v4
      with:
        name: provenance
        path: ${{ steps.build.outputs.provenance }}
