name: "Build with provenance"
on:
  workflow_dispatch:
    inputs:
      target:
        required: true
      build-args:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build with provenance
      id: build
      uses: joinemm/nix-provenance/build-wrapper@master
      with:
        target: ${{ github.event.inputs.target}}
        build-args: ${{ github.event.inputs.build-args }}
        install-nix: 'false'

    - name: Preview provenance
      run: cat ${{ steps.build.outputs.provenance }} | jq .

    - name: Upload provenance artifact
      uses: actions/upload-artifact@v4
      with:
        name: provenance
        path: ${{ steps.build.outputs.provenance }}
